/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReadingProgressRouteImport } from './routes/reading-progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ReadBookRouteImport } from './routes/read.$book'
import { Route as QuizBookRouteImport } from './routes/quiz.$book'
import { Route as QuizSetupBookRouteImport } from './routes/quiz-setup.$book'
import { Route as ProfileEditRouteImport } from './routes/profile_.edit'
import { Route as ProfileChangePasswordRouteImport } from './routes/profile_.change-password'
import { Route as BookBookRouteImport } from './routes/book.$book'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google-callback'
import { Route as ApiVerseExplainRouteImport } from './routes/api/verse-explain'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminQuestionsImportRouteImport } from './routes/admin.questions-import'
import { Route as AdminLanguagesRouteImport } from './routes/admin.languages'
import { Route as AdminBooksRouteImport } from './routes/admin.books'
import { Route as AdminBibleImportRouteImport } from './routes/admin.bible-import'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingProgressRoute = ReadingProgressRouteImport.update({
  id: '/reading-progress',
  path: '/reading-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ReadBookRoute = ReadBookRouteImport.update({
  id: '/read/$book',
  path: '/read/$book',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizBookRoute = QuizBookRouteImport.update({
  id: '/quiz/$book',
  path: '/quiz/$book',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSetupBookRoute = QuizSetupBookRouteImport.update({
  id: '/quiz-setup/$book',
  path: '/quiz-setup/$book',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile_/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileChangePasswordRoute = ProfileChangePasswordRouteImport.update({
  id: '/profile_/change-password',
  path: '/profile/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookRoute = BookBookRouteImport.update({
  id: '/book/$book',
  path: '/book/$book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google-callback',
  path: '/auth/google-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerseExplainRoute = ApiVerseExplainRouteImport.update({
  id: '/api/verse-explain',
  path: '/api/verse-explain',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsImportRoute = AdminQuestionsImportRouteImport.update({
  id: '/questions-import',
  path: '/questions-import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLanguagesRoute = AdminLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBibleImportRoute = AdminBibleImportRouteImport.update({
  id: '/bible-import',
  path: '/bible-import',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reading-progress': typeof ReadingProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/statistics': typeof StatisticsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/bible-import': typeof AdminBibleImportRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/questions-import': typeof AdminQuestionsImportRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/verse-explain': typeof ApiVerseExplainRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/book/$book': typeof BookBookRoute
  '/profile/change-password': typeof ProfileChangePasswordRoute
  '/profile/edit': typeof ProfileEditRoute
  '/quiz-setup/$book': typeof QuizSetupBookRoute
  '/quiz/$book': typeof QuizBookRoute
  '/read/$book': typeof ReadBookRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reading-progress': typeof ReadingProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/statistics': typeof StatisticsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/bible-import': typeof AdminBibleImportRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/questions-import': typeof AdminQuestionsImportRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/verse-explain': typeof ApiVerseExplainRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/book/$book': typeof BookBookRoute
  '/profile/change-password': typeof ProfileChangePasswordRoute
  '/profile/edit': typeof ProfileEditRoute
  '/quiz-setup/$book': typeof QuizSetupBookRoute
  '/quiz/$book': typeof QuizBookRoute
  '/read/$book': typeof ReadBookRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reading-progress': typeof ReadingProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/statistics': typeof StatisticsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/bible-import': typeof AdminBibleImportRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/questions-import': typeof AdminQuestionsImportRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/verse-explain': typeof ApiVerseExplainRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/book/$book': typeof BookBookRoute
  '/profile_/change-password': typeof ProfileChangePasswordRoute
  '/profile_/edit': typeof ProfileEditRoute
  '/quiz-setup/$book': typeof QuizSetupBookRoute
  '/quiz/$book': typeof QuizBookRoute
  '/read/$book': typeof ReadBookRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/profile'
    | '/reading-progress'
    | '/reset-password'
    | '/search'
    | '/statistics'
    | '/verify-email'
    | '/admin/bible-import'
    | '/admin/books'
    | '/admin/languages'
    | '/admin/questions-import'
    | '/admin/users'
    | '/api/verse-explain'
    | '/auth/google-callback'
    | '/book/$book'
    | '/profile/change-password'
    | '/profile/edit'
    | '/quiz-setup/$book'
    | '/quiz/$book'
    | '/read/$book'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/profile'
    | '/reading-progress'
    | '/reset-password'
    | '/search'
    | '/statistics'
    | '/verify-email'
    | '/admin/bible-import'
    | '/admin/books'
    | '/admin/languages'
    | '/admin/questions-import'
    | '/admin/users'
    | '/api/verse-explain'
    | '/auth/google-callback'
    | '/book/$book'
    | '/profile/change-password'
    | '/profile/edit'
    | '/quiz-setup/$book'
    | '/quiz/$book'
    | '/read/$book'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/profile'
    | '/reading-progress'
    | '/reset-password'
    | '/search'
    | '/statistics'
    | '/verify-email'
    | '/admin/bible-import'
    | '/admin/books'
    | '/admin/languages'
    | '/admin/questions-import'
    | '/admin/users'
    | '/api/verse-explain'
    | '/auth/google-callback'
    | '/book/$book'
    | '/profile_/change-password'
    | '/profile_/edit'
    | '/quiz-setup/$book'
    | '/quiz/$book'
    | '/read/$book'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReadingProgressRoute: typeof ReadingProgressRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  StatisticsRoute: typeof StatisticsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiVerseExplainRoute: typeof ApiVerseExplainRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  BookBookRoute: typeof BookBookRoute
  ProfileChangePasswordRoute: typeof ProfileChangePasswordRoute
  ProfileEditRoute: typeof ProfileEditRoute
  QuizSetupBookRoute: typeof QuizSetupBookRoute
  QuizBookRoute: typeof QuizBookRoute
  ReadBookRoute: typeof ReadBookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading-progress': {
      id: '/reading-progress'
      path: '/reading-progress'
      fullPath: '/reading-progress'
      preLoaderRoute: typeof ReadingProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/read/$book': {
      id: '/read/$book'
      path: '/read/$book'
      fullPath: '/read/$book'
      preLoaderRoute: typeof ReadBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$book': {
      id: '/quiz/$book'
      path: '/quiz/$book'
      fullPath: '/quiz/$book'
      preLoaderRoute: typeof QuizBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-setup/$book': {
      id: '/quiz-setup/$book'
      path: '/quiz-setup/$book'
      fullPath: '/quiz-setup/$book'
      preLoaderRoute: typeof QuizSetupBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/edit': {
      id: '/profile_/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/change-password': {
      id: '/profile_/change-password'
      path: '/profile/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof ProfileChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$book': {
      id: '/book/$book'
      path: '/book/$book'
      fullPath: '/book/$book'
      preLoaderRoute: typeof BookBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google-callback': {
      id: '/auth/google-callback'
      path: '/auth/google-callback'
      fullPath: '/auth/google-callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verse-explain': {
      id: '/api/verse-explain'
      path: '/api/verse-explain'
      fullPath: '/api/verse-explain'
      preLoaderRoute: typeof ApiVerseExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions-import': {
      id: '/admin/questions-import'
      path: '/questions-import'
      fullPath: '/admin/questions-import'
      preLoaderRoute: typeof AdminQuestionsImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/languages': {
      id: '/admin/languages'
      path: '/languages'
      fullPath: '/admin/languages'
      preLoaderRoute: typeof AdminLanguagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bible-import': {
      id: '/admin/bible-import'
      path: '/bible-import'
      fullPath: '/admin/bible-import'
      preLoaderRoute: typeof AdminBibleImportRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBibleImportRoute: typeof AdminBibleImportRoute
  AdminBooksRoute: typeof AdminBooksRoute
  AdminLanguagesRoute: typeof AdminLanguagesRoute
  AdminQuestionsImportRoute: typeof AdminQuestionsImportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBibleImportRoute: AdminBibleImportRoute,
  AdminBooksRoute: AdminBooksRoute,
  AdminLanguagesRoute: AdminLanguagesRoute,
  AdminQuestionsImportRoute: AdminQuestionsImportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReadingProgressRoute: ReadingProgressRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  StatisticsRoute: StatisticsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiVerseExplainRoute: ApiVerseExplainRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  BookBookRoute: BookBookRoute,
  ProfileChangePasswordRoute: ProfileChangePasswordRoute,
  ProfileEditRoute: ProfileEditRoute,
  QuizSetupBookRoute: QuizSetupBookRoute,
  QuizBookRoute: QuizBookRoute,
  ReadBookRoute: ReadBookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
